/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controler.ControllerClasse;
import controler.ControllerMedicamento;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Medicamento;

/**
 *
 * @author Garcia
 */
public class FrmVendas_Med extends javax.swing.JFrame {

    List<Medicamento> medicamentos = new ArrayList<Medicamento>();
    ControllerMedicamento controlmed = new ControllerMedicamento();
    ControllerClasse controlclasse = new ControllerClasse();
    int indece, cont;
    
    public FrmVendas_Med() {
        initComponents();
        setLocationRelativeTo( null );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblvendas = new javax.swing.JTable();
        txt_pesquisa = new javax.swing.JTextField();
        btnPesquisa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        label_total = new javax.swing.JLabel();
        btn_finalizar = new javax.swing.JButton();
        lb_soma = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText(" Vendas de Medicamentos!");

        jSeparator1.setForeground(new java.awt.Color(204, 0, 0));

        tblvendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "VALOR", "NOME", "FABRICANTE", "COD BARRAS", "QUANT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblvendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMedicamentosMouseClicked(evt);
            }
        });
        tblvendas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblvendasKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblMedicamentosKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tblvendas);
        if (tblvendas.getColumnModel().getColumnCount() > 0) {
            tblvendas.getColumnModel().getColumn(4).setResizable(false);
        }

        txt_pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pesquisaActionPerformed(evt);
            }
        });

        btnPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/plus (4).png"))); // NOI18N
        btnPesquisa.setText("Adicionar");
        btnPesquisa.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Pesquisar Medicamento:");

        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("QUANTIDADE TOTAL DE ITENS:");

        label_total.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_total.setForeground(new java.awt.Color(0, 153, 153));
        label_total.setText("0");

        btn_finalizar.setBackground(new java.awt.Color(0, 153, 153));
        btn_finalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/coin (1).png"))); // NOI18N
        btn_finalizar.setText("Finalizar Venda");
        btn_finalizar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btn_finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_finalizarActionPerformed(evt);
            }
        });

        lb_soma.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_soma.setForeground(new java.awt.Color(0, 153, 153));
        lb_soma.setText("0");

        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("Valor Total:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(114, 114, 114)
                                    .addComponent(label_total)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lb_soma)
                                    .addGap(114, 114, 114))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(53, 53, 53)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4)
                                    .addGap(91, 91, 91)))
                            .addComponent(btn_finalizar))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btn_finalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_total)
                            .addComponent(lb_soma))))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblMedicamentosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblMedicamentosKeyReleased
        int v=0;
        double soma=0;
        if (evt.getKeyCode() == 8) {
            DefaultTableModel modelo = (DefaultTableModel) tblvendas.getModel();
            modelo.setNumRows(cont--);   
            medicamentos.clear();
        }
        if(evt.getKeyCode()==38 || evt.getKeyCode()==40) {
                for (int i = 0; i < medicamentos.size(); i++) {
                     
                      v=v+Integer.parseInt(tblvendas.getModel().getValueAt(i, 4).toString());
                      soma=soma+(Double.parseDouble(tblvendas.getModel().getValueAt(i, 0).toString())*Integer.parseInt(tblvendas.getModel().getValueAt(i, 4).toString()));
            }
                  label_total.setText(String.valueOf(v));
                  lb_soma.setText(String.valueOf(soma));
        }
    }//GEN-LAST:event_tblMedicamentosKeyReleased

    private void tblMedicamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMedicamentosMouseClicked

    }//GEN-LAST:event_tblMedicamentosMouseClicked

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed

        Medicamento n = new Medicamento();
            n = controlmed.buscaMedicamento(txt_pesquisa.getText());
            if(n.getId()==0){
                JOptionPane.showMessageDialog(null,"Medicamento não encontrado!");
             }else{
            medicamentos.add(n);
            tblvendas.getColumnModel().getColumn(0).setPreferredWidth(5);
            tblvendas.getColumnModel().getColumn(1).setPreferredWidth(40);
            tblvendas.getColumnModel().getColumn(2).setPreferredWidth(40);
            tblvendas.getColumnModel().getColumn(3).setPreferredWidth(15);
            tblvendas.getColumnModel().getColumn(4).setPreferredWidth(15);

            DefaultTableModel modelo = (DefaultTableModel) tblvendas.getModel();
            modelo.setNumRows(0);
            double soma=0;
            int v=0;
            cont++;
            for (int i = 0; i < medicamentos.size(); i++) {
                   
                    modelo.addRow(new Object[]{
                        medicamentos.get(i).getValor_med(),
                        medicamentos.get(i).getNome_med(),
                        medicamentos.get(i).getFabricante(),
                        medicamentos.get(i).getCod_barras(),
                         1
                    });
                      soma=soma+Double.parseDouble(tblvendas.getModel().getValueAt(i, 0).toString());
                      v=v+Integer.parseInt(tblvendas.getModel().getValueAt(i, 4).toString());
            }
            
                label_total.setText(String.valueOf(v));
                lb_soma.setText(String.valueOf(soma));
            }
    }//GEN-LAST:event_btnPesquisaActionPerformed

    private void txt_pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pesquisaActionPerformed

    }//GEN-LAST:event_txt_pesquisaActionPerformed

    private void btn_finalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_finalizarActionPerformed
        int opcao = JOptionPane.showConfirmDialog(null,"Deseja finalizar Venda?");
        if (opcao ==0){
            for (int i = 0; i < medicamentos.size(); i++) {
                int quant=Integer.parseInt(tblvendas.getModel().getValueAt(i, 4).toString());
                controlmed.alterarMedicamento(medicamentos.get(i).getId(),medicamentos.get(i).getQuant()-quant);
            }
            String x="", y="",z="";
            for (int i = 0; i < medicamentos.size(); i++) {
                x=medicamentos.get(i).getNome_med()+" "+x;
                y=medicamentos.get(i).getCod_barras()+" "+y;
                z=medicamentos.get(i).getFabricante()+" "+z;
    
            }
            Medicamento med_salvo= new Medicamento();
            med_salvo.setNome_med(x);
            med_salvo.setCod_barras(y);
            med_salvo.setClasse_med(6);
            med_salvo.setQuant(Integer.parseInt(label_total.getText()));
            med_salvo.setValor_med(Double.parseDouble(lb_soma.getText()));
            med_salvo.setFabricante(z);

            controlmed.salvarVenda(med_salvo);
            medicamentos.clear();
            DefaultTableModel modelo = (DefaultTableModel) tblvendas.getModel();
            modelo.setNumRows(0);
            txt_pesquisa.setText("");
            label_total.setText("0");
            lb_soma.setText("");
            JOptionPane.showMessageDialog(null,"Venda efetivada");
            
           
        }else{
            JOptionPane.showMessageDialog(null,"Venda não efetivada");
        }   
    }//GEN-LAST:event_btn_finalizarActionPerformed

    private void tblvendasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblvendasKeyPressed
                            

    }//GEN-LAST:event_tblvendasKeyPressed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVendas_Med.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVendas_Med.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVendas_Med.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVendas_Med.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVendas_Med().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JButton btn_finalizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label_total;
    private javax.swing.JLabel lb_soma;
    private javax.swing.JTable tblvendas;
    private javax.swing.JTextField txt_pesquisa;
    // End of variables declaration//GEN-END:variables
}
