/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controler.ControllerMedicamento;
import controler.ControllerUsuario;
import java.awt.Desktop;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.Usuario;

/**
 *
 * @author Garcia
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
     List<Usuario> lista= new ArrayList<Usuario>();
    ControllerUsuario c= new ControllerUsuario();
    ControllerMedicamento c_med= new ControllerMedicamento();
    int indice;
    public TelaPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        
        
    }
     public TelaPrincipal(int status) {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        if(status==2){
             cad_Med.setVisible(false);
             cad_user.setVisible(false);
        }
       
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        Menu_Med = new javax.swing.JMenu();
        Vendas_Med = new javax.swing.JMenuItem();
        cad_Med = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        gerar_r_estoque_med = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        cad_user = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Menu_Med.setText("Medicamentos");
        Menu_Med.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_MedMouseClicked(evt);
            }
        });

        Vendas_Med.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        Vendas_Med.setText("Vendas Medicamentos");
        Vendas_Med.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Vendas_MedMouseClicked(evt);
            }
        });
        Vendas_Med.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Vendas_MedActionPerformed(evt);
            }
        });
        Menu_Med.add(Vendas_Med);

        cad_Med.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        cad_Med.setText("Gerenciar Medicamentos");
        cad_Med.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cad_MedActionPerformed(evt);
            }
        });
        Menu_Med.add(cad_Med);

        jMenuBar1.add(Menu_Med);

        jMenu3.setText("Relátorio");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        gerar_r_estoque_med.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        gerar_r_estoque_med.setText("Gerar relatório estoque medicamentos");
        gerar_r_estoque_med.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerar_r_estoque_medActionPerformed(evt);
            }
        });
        jMenu3.add(gerar_r_estoque_med);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Gerar relatório de vendas efetivadas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Sistema");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        cad_user.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        cad_user.setText("Cadastrar Usuário");
        cad_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cad_userActionPerformed(evt);
            }
        });
        jMenu1.add(cad_user);

        jMenuBar1.add(jMenu1);

        jMenu9.setText("Sair");
        jMenu9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu9MouseClicked(evt);
            }
        });
        jMenu9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu9ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Vendas_MedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Vendas_MedMouseClicked
        TelaPrincipal tl= new TelaPrincipal();
        

    }//GEN-LAST:event_Vendas_MedMouseClicked

    private void Vendas_MedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Vendas_MedActionPerformed
         new FrmVendas_Med().show();
       

    }//GEN-LAST:event_Vendas_MedActionPerformed

    private void cad_MedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cad_MedActionPerformed
       
        new FrmCad_Med().show();
    }//GEN-LAST:event_cad_MedActionPerformed

    private void Menu_MedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_MedMouseClicked

    }//GEN-LAST:event_Menu_MedMouseClicked

    private void jMenu9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu9MouseClicked
        int op=JOptionPane.showConfirmDialog(null, "Você realmente deseja fechar o sistema?","Sair",JOptionPane.YES_NO_OPTION);
        if(op==0){
            System.exit(0);
        }else{
            return;
        }
    }//GEN-LAST:event_jMenu9MouseClicked

    private void jMenu9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu9ActionPerformed

    }//GEN-LAST:event_jMenu9ActionPerformed

    private void cad_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cad_userActionPerformed
       new FrmCadUsuario().show();
    }//GEN-LAST:event_cad_userActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
    
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void gerar_r_estoque_medActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerar_r_estoque_medActionPerformed
       c_med.GerarRelatorioEstoqueMedicamentos();
    }//GEN-LAST:event_gerar_r_estoque_medActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
         c_med.GerarRelatorioVenda();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu_Med;
    private javax.swing.JMenuItem Vendas_Med;
    private javax.swing.JMenuItem cad_Med;
    private javax.swing.JMenuItem cad_user;
    private javax.swing.JMenuItem gerar_r_estoque_med;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
